//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestoApp_Afonichev.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChequePosition
    {
        public int ChequePositionId { get; set; }
        public int ChequeId { get; set; }
        public int PositionId { get; set; }
    
        public virtual Cheque Cheque { get; set; }
        public virtual Position Position { get; set; }
    }
}
