//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestoApp_Afonichev.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public Employee()
        {
            this.Cheque = new HashSet<Cheque>();
        }
    
        public int EmployeeId { get; set; }
        public string Name { get; set; }
        public string Pincode { get; set; }
        public int RoleId { get; set; }
    
        public virtual ICollection<Cheque> Cheque { get; set; }
        public virtual Role Role { get; set; }
    }
}
